version: '3.8'

services:
  api:
    build: './api'
    container_name: 'api'
    ports:
      - '4000:4000'
    volumes:
      - './api:/api'
      - 'compose_node_modules_api:/api/node_modules'

  app:
    build: './app'
    container_name: 'app'
    ports:
      - '3000:3000'
    volumes:
      - './app:/app'
      - 'compose_node_modules_app:/app/node_modules'
    stdin_open: true
    tty: true

volumes:
  compose_node_modules_api:
  compose_node_modules_app: