version: '3.8'
services:
  backend: 
    build: './api'
    container_name: 'backend_c1'
    ports:
      - '4000:4000'
    volumes:
      - './api:/app'
      - '/app/node_modules'
  frontend:
    build: './app'
    container_name: 'frontend_c1'
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    # volumes:
    #   - './app:/app'
    #   - '/app/node_modules'